name: Build and Publish Image to Docker Hub

on:
  workflow_dispatch

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u zitguy316 --password-stdin

      - name: Build image
        run: docker build ./contactapi/ -t zitguy316/contact-list:latest

      - name: Push image to Docker Hub
        run: docker push zitguy316/contact-list:latest
